### PR TITLE
find settings are stored (on quit) and restored (on load)

### PR DESCRIPTION
**Pull request by Freaxed**
Saving settings for Wrap, Whole Word and Match Case.

### CODE REVIEW

**Review by nexus6-haiku — COMMENTED** [review]
What is the purpose of finding a specific value in the BMessage before setting its value?
AFAIK the new Set* members should already do this internally

**Comment by Freaxed** [comment]
Regarding my patch: I followed the path on how to manage a config setting without thinking too much on the current code. In general you are right: the Set shoul perform the check and call Add or Replace accordingly.. anyway the code is just adding to the setting the missing keys with the default values.. so replacing with just the Set* will override the values with the defaults.. not sure is the expected behaviour. We should look at the whole setting loading and saving lifecicle to better understand it.

**Comment by nexus6-haiku** [comment]
Of course, it wasn't specifically aimed at your patch. I hoped you had a better understanding of how settings are managed because there seem to be many inconsistencies all around the code.
I agree, let's look at this later to rationalize how settings are managed possibly into one file only managed by a central class (for application-wide settings)

**Comment by nexus6-haiku** [comment]
Happy to merge it

**Pull request merged**
