### PR TITLE
Feature/new tool bar

### PR DESCRIPTION
**Pull request by Freaxed**
Using Koder's toolbar: based on BToolBar with dynamic icon size.

### CODE REVIEW

**Comment by jackburton79** [comment]
Nice! Shouldn't it go under UI, though?

**Comment by Freaxed** [comment]
ToolBar class moved..
By default the new icon size is 32 pixels, smaller than the legacy version. The icons start from the left border of the toolbar. We should review the order of the buttons, add the missing (like the open project) and remove the useless ones.

 As soon as we have a better way for setting the configuration we can add some option to express the preferred icon size.

**Comment by nexus6-haiku** [comment]
Looks ok but I would keep using fToolbar for the name of the instance variable

**Comment by Freaxed** [comment]
done!

**Pull request merged**
