### PR TITLE
Feature/console io files

### PR DESCRIPTION
**Pull request by Freaxed**
Even if the golden solution is to implement a set of regex to grab compiler errors and show them in a nice listview (with suggestions, quickfixes and integrated with LSP diagnostics), I implemented this simple algo to identify inside the console-io panel (BTextView) all the valid file paths (including line and column information). It doesn't have any impact on the overall design and all the code is isolated inside a BTextView subclass.

### CODE REVIEW

**Comment by nexus6-haiku** [comment]
Yes, it's not optimal but it works! Can you please keep track of this tech debt when it's ready to merge?

**Comment by Freaxed** [comment]
Why are you saying it's not optimal? Do you see any problem in the code or are you referring to the overall solution?

**Comment by Freaxed** [comment]
Anyway, I opened an Issues to track the feature we would like to implement..
The development on this branch is close and can be merged (unless you find some bugs or issues)

**Comment by nexus6-haiku** [comment]
I'm speaking of the overall solution as you have acknowledged in the issue.
I haven't found any bug and I am happy to merge it

**Pull request merged**
