### PR TITLE
Added Comment/Uncomment of selected lines

### PR DESCRIPTION
**Pull request by nexus6-haiku**
Added a dedicated menu item with shortcut
Modified the behaviour of clicking the Editor margin to comment/uncomment selected lines, as well

### CODE REVIEW

**Comment by nexus6-haiku** [comment]
I thought it is a typo, isn't it?

**Comment by nexus6-haiku** [comment]
I thought it is a typo, isn't it?

**Comment by nexus6-haiku** [comment]
Shortcuts are case insensitive unless B_SHIFT_KEY is explicitly set.
Here's an excerpt from BMenuItem documentation from BeBook:

> Upper case characters are mapped to lower case characters; if you want the user to have to type an upper case character, you must include B_SHIFT_KEY in the modifers mask.

**Comment by Freaxed** [comment]
Not sure if this is the expected result: open a file, select the first 5 lines, click on the margin at line 10.. you are now commenting the line 1->6 and nothing happen on line 10..

**Comment by nexus6-haiku** [comment]
Good question, maybe the margin-click is not the right tool for this and should be used only to comment/uncomment the line where the click happens.
We may leave the "comment/uncomment selected lines" as a separate feature accessible via menu item and its shortcut.
Sounds better?

**Comment by Freaxed** [comment]
Ok, let's keep the margin click only for  commenting single lines then.

Il giorno lun 27 mar 2023 alle ore 16:06 Davide Alfano <
***@***.***> ha scritto:

**Pull request merged**
